-- P7: defaults, the screen's explicit lock capability, and audience safety.
begin;
select no_plan();
create temporary table p7_state (key text primary key, value jsonb);
grant all on p7_state to authenticated;
insert into auth.users (id, is_anonymous) select ('a7777777-0000-0000-0000-00000000000' || n)::uuid, true from generate_series(1,7) n;
create function pg_temp.as_user(n int) returns void language sql as $$
 select set_config('request.jwt.claim.sub', 'a7777777-0000-0000-0000-00000000000' || n, true);
$$;
create function pg_temp.room() returns uuid language sql as $$ select (value->>'roomId')::uuid from p7_state where key='room'; $$;
create function pg_temp.seat(k text) returns uuid language sql as $$ select (value->>'playerId')::uuid from p7_state where key=k; $$;
create function pg_temp.member() returns uuid language sql as $$ select (value->>'id')::uuid from p7_state where key='member'; $$;
set local role authenticated;
select pg_temp.as_user(1);
insert into p7_state values ('room',public.create_party_room('ludo'));
select is((public.get_party_screen(pg_temp.room())->>'partyTurnSeconds')::int,30,'new Party tables use 30 seconds');
select throws_ok(format('select public.set_party_locked(%L,true)',pg_temp.room()),'P0001','INVALID_PHASE','screen cannot lock before the game');
select pg_temp.as_user(2);
insert into p7_state values ('vip',public.join_room_by_id(pg_temp.room(),'Ana'));
select pg_temp.as_user(3);
insert into p7_state values ('phone',public.join_room_by_id(pg_temp.room(),'Ben'));
reset role;
select is(private.ludo_next_turn_deadline(pg_temp.seat('vip')) - now(),interval '30 seconds','Party human deadline is 30 seconds');
select is((select private.ludo_resolve_rules(rules)->>'bonusRollOnFinish' from public.rooms where id=pg_temp.room()),'true','Family keeps finish bonus on');
set local role authenticated;
select pg_temp.as_user(2);
select public.fill_bot(pg_temp.room(),2);
select public.fill_bot(pg_temp.room(),3);
select public.start_match(pg_temp.room());
select throws_ok(format('select public.set_party_locked(%L,true)',pg_temp.room()),'P0001','ROOM_NOT_FOUND','VIP cannot change display lock');
select pg_temp.as_user(1);
select lives_ok(format('select public.set_party_locked(%L,true)',pg_temp.room()),'screen locks after start');
select is(public.get_party_screen(pg_temp.room())->>'partyLocked','true','lock is visible');
select pg_temp.as_user(4);
select lives_ok(format('select public.join_party_audience(%L,%L)',pg_temp.room(),'shit'),'locked rooms still admit audience');
insert into p7_state select 'member', m from jsonb_array_elements(public.get_party_extras(pg_temp.room())->'audienceMembers') m where (m->>'isMe')::boolean;
select is((select value->>'name' from p7_state where key='member'),'****','audience names use existing server filter');
select ok(private.party_audience_topic_allowed(public.get_party_extras(pg_temp.room())->>'audienceTopic'),'audience can subscribe to its own topic');
select lives_ok(format('select public.report_player(%L,%L,%L)',pg_temp.room(),pg_temp.seat('vip'),'other'),'audience can report a seated player');
select throws_ok(format('select public.report_party_audience(%L,%L,%L)',pg_temp.room(),pg_temp.member(),'other'),'P0001','PLAYER_NOT_FOUND','cannot report self');
select pg_temp.as_user(5);
select public.join_party_audience(pg_temp.room(),'Fan Two');
select ok(not private.party_audience_topic_allowed('audience:' || pg_temp.member()::text),'another audience member cannot subscribe to this topic');
select lives_ok(format('select public.report_party_audience(%L,%L,%L)',pg_temp.room(),pg_temp.member(),'hate'),'audience can report audience');
select throws_ok(format('select public.remove_party_audience(%L,%L)',pg_temp.room(),pg_temp.member()),'P0001','NOT_HOST','audience cannot remove audience');
select pg_temp.as_user(6);
select throws_ok(format('select public.report_party_audience(%L,%L,%L)',pg_temp.room(),pg_temp.member(),'other'),'P0001','ROOM_NOT_FOUND','outsider cannot report audience');
select pg_temp.as_user(1);
select throws_ok(format('select public.remove_party_audience(%L,%L)',pg_temp.room(),pg_temp.member()),'P0001','NOT_HOST','display cannot remove audience');
select throws_ok(format('select public.report_party_audience(%L,%L,%L)',pg_temp.room(),pg_temp.member(),'other'),'P0001','ROOM_NOT_FOUND','display cannot report');
select pg_temp.as_user(3);
select throws_ok(format('select public.remove_party_audience(%L,%L)',pg_temp.room(),pg_temp.member()),'P0001','NOT_HOST','non-VIP player cannot remove audience');
select pg_temp.as_user(2);
select throws_ok(format('select public.report_party_audience(%L,%L,%L)',pg_temp.room(),pg_temp.member(),'invalid'),'P0001','INVALID_REPORT','report reason validated');
select lives_ok(format('select public.report_party_audience(%L,%L,%L)',pg_temp.room(),pg_temp.member(),'other'),'player can report audience');
select lives_ok(format('select public.remove_party_audience(%L,%L)',pg_temp.room(),pg_temp.member()),'VIP removes audience');
select pg_temp.as_user(4);
select throws_ok(format('select public.get_audience_state(%L)',pg_temp.room()),'P0001','NOT_AUDIENCE','removed member cannot read state');
select throws_ok(format('select public.audience_react(%L,%L)',pg_temp.room(),'👏'),'P0001','NOT_AUDIENCE','removed member cannot react');
select throws_ok(format('select public.join_party_audience(%L,%L)',pg_temp.room(),'Again'),'P0001','PARTY_REMOVED','removal prevents same-account rejoin');
select ok(not private.party_audience_topic_allowed('audience:' || pg_temp.member()::text),'removed member cannot resubscribe');
reset role;
select is((select count(*)::int from public.player_reports where room_id=pg_temp.room()),3,'reports retain seat and audience evidence');
-- A rematch lobby retains the screen lock. Existing seats still reconnect.
update public.rooms set status='lobby' where id=pg_temp.room();
delete from public.players where room_id=pg_temp.room() and seat_index=3;
set local role authenticated;
select pg_temp.as_user(6);
select throws_ok(format('select public.join_room_by_id(%L,%L)',pg_temp.room(),'Late seat'),'P0001','PARTY_LOCKED','lock blocks new seats between matches');
select lives_ok(format('select public.join_party_audience(%L,%L)',pg_temp.room(),'Late fan'),'locked lobby admits audience even with open seats');
select pg_temp.as_user(4);
select throws_ok(format('select public.join_room_by_id(%L,%L)',pg_temp.room(),'Again'),'P0001','PARTY_LOCKED','removed account cannot switch to seat while locked');
select pg_temp.as_user(2);
select lives_ok(format('select public.join_room_by_id(%L,%L)',pg_temp.room(),'Ana'),'existing player can return to locked lobby');
reset role;
update public.rooms set status='summary' where id=pg_temp.room();
set local role authenticated;
select pg_temp.as_user(1);
select lives_ok(format('select public.set_party_locked(%L,false)',pg_temp.room()),'screen can unlock between games');
reset role;
update public.rooms set status='lobby' where id=pg_temp.room();
set local role authenticated;
select pg_temp.as_user(4);
select throws_ok(format('select public.join_room_by_id(%L,%L)',pg_temp.room(),'Again'),'P0001','PARTY_REMOVED','removed account cannot take an unlocked seat either');
select pg_temp.as_user(7);
insert into p7_state values ('normal',public.create_room('Normal',null,2));
reset role;
select is(private.ludo_next_turn_deadline(pg_temp.seat('normal'))-now(),interval '15 seconds','ordinary tables retain 15-second turns');
select throws_ok(format('select private.matchmaking_matched(%L)',pg_temp.room()),'P0001','NOT_MATCHMAKING_ROOM','quick-match response rejects Party rooms');
-- A bad queue assignment cannot escape via matchmake or cancel.
insert into public.matchmaking_queue(user_id,display_name,game_type,player_count,room_id)
values ('a7777777-0000-0000-0000-000000000007','Normal','ludo',2,pg_temp.room());
set local role authenticated;
select pg_temp.as_user(7);
select throws_ok($$select public.matchmake('ludo','Normal',2)$$,'P0001','NOT_MATCHMAKING_ROOM','matchmake cannot return a Party room');
select throws_ok($$select public.cancel_matchmaking()$$,'P0001','NOT_MATCHMAKING_ROOM','cancel cannot return a Party room');
select * from finish();
rollback;
