import type { Metadata, Viewport } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import Script from "next/script";
import { BRAND } from "@/lib/brand";
import { NativeShell } from "@/components/NativeShell";
import { I18nProvider } from "@/lib/i18n";
import { PreferencesSync } from "@/components/preferences/PreferencesSync";
import { AgeGateOnSignIn } from "@/components/auth/AgeGateOnSignIn";
import { PushRegistration } from "@/components/preferences/PushRegistration";
import "./globals.css";

// Publishes the real visible viewport height to CSS as `--app-height`, so
// full-height containers can size to window.innerHeight instead of trusting
// `dvh`. Some browsers (notably the LG webOS TV browser) parse `dvh`/`svh`
// as valid unit tokens but compute them to 0, which silently overrides a
// `vh` fallback and collapses the layout; innerHeight is correct everywhere,
// and (unlike vh) already excludes the mobile URL bar. Kept as an ES5-only
// inline string so it runs even where the app's modern JS bundle does not.
const APP_HEIGHT_SCRIPT = `(function(){function s(){try{document.documentElement.style.setProperty('--app-height',window.innerHeight+'px');}catch(e){}}s();if(window.addEventListener){window.addEventListener('resize',s);window.addEventListener('orientationchange',s);window.addEventListener('load',s);}})();`;

// Feature-detects flexbox `gap` (Chrome 84+/Safari 14.1+). Browsers without it
// (e.g. webOS TVs on Chromium 79) get html.no-flex-gap, which activates the
// margin fallbacks generated by postcss/flex-gap-fallback.cjs. Runs in <head>
// before first paint, so spacing is correct from the first render (no flash).
const FLEX_GAP_DETECT = `(function(){try{var f=document.createElement('div');f.style.cssText='display:flex;flex-direction:column;row-gap:1px;position:absolute;visibility:hidden;pointer-events:none';var a=document.createElement('div'),b=document.createElement('div');a.style.height='1px';b.style.height='1px';f.appendChild(a);f.appendChild(b);(document.body||document.documentElement).appendChild(f);var ok=f.scrollHeight>=3;if(f.parentNode)f.parentNode.removeChild(f);if(!ok){document.documentElement.className+=(document.documentElement.className?' ':'')+'no-flex-gap';}}catch(e){}})();`;

// "Modern Boardroom" design system (designs/modern_boardroom/DESIGN.md):
// Plus Jakarta Sans for its geometric clarity and tall x-height, mirroring
// native SF Pro rendering across mobile densities.
const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

const title = `${BRAND.name} – Play ${BRAND.gameName} Online with Friends`;
const description = `Play ${BRAND.gameName} online with friends and family on ${BRAND.name}. Create a private room, invite your friends, and enjoy multiplayer ${BRAND.gameName} online.`;

export const metadata: Metadata = {
  metadataBase: new URL(BRAND.url),
  title,
  description,
  alternates: { canonical: "/" },
  applicationName: BRAND.name,
  openGraph: {
    title,
    description,
    url: "/",
    siteName: BRAND.name,
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

// viewport-fit=cover lets env(safe-area-inset-*) resolve to real, non-zero
// values on notched/rounded-corner devices — simulator.css already relies
// on them.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

const isAppBuild = !!process.env.CAPACITOR_BUILD;

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: BRAND.name,
  alternateName: BRAND.tagline,
  description: BRAND.description,
  url: BRAND.url,
  applicationCategory: "GameApplication",
  genre: `${BRAND.gameName} board game`,
  operatingSystem: "Any",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${plusJakartaSans.variable} h-full antialiased`}>
      {/* JSON-LD lives in <head>, not <body>: PostHog (instrumentation-client.ts)
          injects its loader <script> next to the body's existing scripts before
          React hydrates, and a React-rendered script there made every page
          report a hydration mismatch. */}
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* Sets --app-height before first paint so full-height containers never
            depend on dvh (which some TV browsers compute to 0). See the
            APP_HEIGHT_SCRIPT comment above. */}
        <script dangerouslySetInnerHTML={{ __html: APP_HEIGHT_SCRIPT }} />
        {/* Flags browsers without flexbox gap so the CSS margin fallbacks apply. */}
        <script dangerouslySetInnerHTML={{ __html: FLEX_GAP_DETECT }} />
      </head>
      <body className="min-h-full flex flex-col">
        {/* F5.1: client-side locale detection + <html lang/dir> sync. The
            server always renders the default (English) HTML above; the
            provider adopts the player's locale right after mount. */}
        <I18nProvider>
          <PreferencesSync />
          <AgeGateOnSignIn />
          <PushRegistration />
          {children}
          <NativeShell />
        </I18nProvider>
      </body>
      {/* Web only: the app build (CAPACITOR_BUILD) leaves out Google
          Analytics' marketing tracking, keeping the App Store privacy label
          to the product analytics declared in ios/App/App/PrivacyInfo.xcprivacy. */}
      {!isAppBuild && (
        <>
          <Script
            src="https://www.googletagmanager.com/gtag/js?id=G-75GZQ69MCG"
            strategy="afterInteractive"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-75GZQ69MCG');`}
          </Script>
        </>
      )}
    </html>
  );
}
