/**
 * Writes the Google Tag Manager container for Luddo House
 * (docs/gtm-container.json) from the event catalog in lib/analytics/events.ts,
 * so the container can never drift from what the code sends.
 *
 *   npm run analytics:gtm -- 6380212474 265907052   (GTM account and container ids)
 *
 * Import the file in GTM (Admin → Import Container → an unpublished
 * workspace → Merge, "Rename conflicting tags, triggers and variables"),
 * check it in Preview, then publish. docs/analytics.md has the whole routine.
 *
 * What it builds:
 * - a Data Layer Variable per event parameter (`luddo.<name>`), per page key
 *   (`page_location`, `page_referrer`, `page_title`) and per user property
 *   (`luddo_user.<name>`);
 * - "Event Settings - Luddo", which gives every hit the cleaned page and the
 *   user properties;
 * - "Google tag - Luddo House", fired once on `luddo_ready` (only the app's
 *   code pushes it), with page views off: the app sends its own;
 * - "GA4 Event - Luddo catalog", fired on any catalog event name, sending
 *   `{{Event}}` with every parameter that has a value;
 * - both tags need `analytics_storage` (Consent Mode, basic): where it is
 *   denied by default (EEA, UK, Switzerland), nothing fires.
 */
import { writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { EVENT_NAMES, PARAMETER_NAMES, USER_PROPERTY_NAMES } from "../lib/analytics/events";

export const GA_MEASUREMENT_ID = "G-75GZQ69MCG";
export const GTM_PUBLIC_ID = "GTM-N7X49V9F";
export const READY_EVENT = "luddo_ready";

/** Page keys pushed at the top level of the data layer (lib/analytics/destinations.ts). */
const PAGE_KEYS = ["page_location", "page_referrer", "page_title"] as const;

type Parameter =
  | { type: "TEMPLATE" | "BOOLEAN" | "INTEGER"; key?: string; value: string }
  | { type: "LIST"; key: string; list: Parameter[] }
  | { type: "MAP"; key?: string; map: Parameter[] };

interface GtmVariable {
  accountId: string;
  containerId: string;
  variableId: string;
  name: string;
  type: string;
  parameter: Parameter[];
  notes: string;
}

const template = (key: string, value: string): Parameter => ({ type: "TEMPLATE", key, value });
const row = (entries: [string, string][]): Parameter => ({
  type: "MAP",
  map: entries.map(([key, value]) => template(key, value)),
});

export const dlvName = (path: string) => `DLV - ${path}`;

/** The regex the catalog trigger matches: exactly one of the catalog's event names. */
export function catalogRegex(): string {
  return `^(${EVENT_NAMES.join("|")})$`;
}

export function buildGtmContainer(ids: { accountId: string; containerId: string } = { accountId: "0", containerId: "0" }) {
  const base = { accountId: ids.accountId, containerId: ids.containerId };
  let nextId = 1;
  const id = () => String(nextId++);

  const dataLayerVariable = (path: string): GtmVariable => ({
    ...base,
    variableId: id(),
    name: dlvName(path),
    type: "v",
    parameter: [
      { type: "INTEGER", key: "dataLayerVersion", value: "2" },
      { type: "BOOLEAN", key: "setDefaultValue", value: "false" },
      template("name", path),
    ],
    notes: "Generated by scripts/generate-gtm-container.ts. Do not edit in GTM.",
  });

  const eventParameters = PARAMETER_NAMES.filter((name) => !(PAGE_KEYS as readonly string[]).includes(name));
  const variables: GtmVariable[] = [
    ...PAGE_KEYS.map(dataLayerVariable),
    ...eventParameters.map((name) => dataLayerVariable(`luddo.${name}`)),
    ...USER_PROPERTY_NAMES.map((name) => dataLayerVariable(`luddo_user.${name}`)),
  ];

  const eventSettings: GtmVariable = {
    ...base,
    variableId: id(),
    name: "Event Settings - Luddo",
    type: "gtes",
    parameter: [
      {
        type: "LIST",
        key: "eventSettingsTable",
        list: PAGE_KEYS.map((key) => row([["parameter", key], ["parameterValue", `{{${dlvName(key)}}}`]])),
      },
      {
        type: "LIST",
        key: "userProperties",
        list: USER_PROPERTY_NAMES.map((name) =>
          row([["name", name], ["value", `{{${dlvName(`luddo_user.${name}`)}}}`]]),
        ),
      },
    ],
    notes: "Cleaned page and user properties for every hit. Generated; do not edit in GTM.",
  };
  variables.push(eventSettings);

  const customEvent = (name: string, filterType: "EQUALS" | "MATCH_REGEX", value: string) => ({
    ...base,
    triggerId: id(),
    name,
    type: "CUSTOM_EVENT",
    customEventFilter: [
      {
        type: filterType,
        parameter: [template("arg0", "{{_event}}"), template("arg1", value)],
      },
    ],
    notes: "Generated by scripts/generate-gtm-container.ts.",
  });

  const readyTrigger = customEvent(`CE - ${READY_EVENT}`, "EQUALS", READY_EVENT);
  const catalogTrigger = customEvent("CE - Luddo catalog", "MATCH_REGEX", catalogRegex());

  const needsAnalyticsStorage = {
    consentStatus: "NEEDED",
    consentType: { type: "LIST", list: [{ type: "TEMPLATE", value: "analytics_storage" }] },
  };

  const googleTag = {
    ...base,
    tagId: id(),
    name: "Google tag - Luddo House",
    type: "googtag",
    parameter: [
      template("tagId", GA_MEASUREMENT_ID),
      {
        type: "LIST",
        key: "configSettingsTable",
        list: [row([["parameter", "send_page_view"], ["parameterValue", "false"]])],
      },
      template("eventSettingsVariable", `{{${eventSettings.name}}}`),
    ],
    firingTriggerId: [readyTrigger.triggerId],
    tagFiringOption: "ONCE_PER_LOAD",
    consentSettings: needsAnalyticsStorage,
    monitoringMetadata: { type: "MAP" },
    notes: `Fires once on ${READY_EVENT}, which only the app's code pushes. Page views come from the app.`,
  };

  const eventTag = {
    ...base,
    tagId: id(),
    name: "GA4 Event - Luddo catalog",
    type: "gaawe",
    parameter: [
      template("eventName", "{{Event}}"),
      template("measurementIdOverride", GA_MEASUREMENT_ID),
      { type: "BOOLEAN", key: "sendEcommerceData", value: "false" },
      { type: "BOOLEAN", key: "enhancedUserId", value: "false" },
      {
        type: "LIST",
        key: "eventSettingsTable",
        list: eventParameters.map((name) =>
          row([["parameter", name], ["parameterValue", `{{${dlvName(`luddo.${name}`)}}}`]]),
        ),
      },
      template("eventSettingsVariable", `{{${eventSettings.name}}}`),
    ],
    firingTriggerId: [catalogTrigger.triggerId],
    tagFiringOption: "ONCE_PER_EVENT",
    consentSettings: needsAnalyticsStorage,
    monitoringMetadata: { type: "MAP" },
    notes: "Every catalog event, with whichever parameters it carries. Generated; do not edit in GTM.",
  };

  return {
    exportFormatVersion: 2,
    exportTime: new Date().toISOString().replace("T", " ").slice(0, 19),
    containerVersion: {
      ...base,
      containerVersionId: "0",
      container: { ...base, name: "Luddo House", publicId: GTM_PUBLIC_ID, usageContext: ["WEB"] },
      tag: [googleTag, eventTag],
      trigger: [readyTrigger, catalogTrigger],
      variable: variables,
      builtInVariable: [{ ...base, type: "EVENT", name: "Event" }],
    },
  };
}

function main() {
  const [accountId = "0", containerId = "0"] = process.argv.slice(2);
  const container = buildGtmContainer({ accountId, containerId });
  const file = new URL("../docs/gtm-container.json", import.meta.url);
  writeFileSync(file, `${JSON.stringify(container, null, 2)}\n`);
  const { tag, trigger, variable } = container.containerVersion;
  console.log(
    `Wrote docs/gtm-container.json: ${tag.length} tags, ${trigger.length} triggers, ${variable.length} variables, ${EVENT_NAMES.length} events.`,
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
